### ISSUE TITLE
Membership Status Change not submitting

### ISSUE THREAD

**Issue by gojiman23** [VenturaFranklin/ThetaTauAnnualReport#197]
Hey Frank,

This is Dylan Siv, the current scribe for Sigma Delta Chapter. Right now when attempting to submit the Membership status change form, after correctly filling out all information and hitting submit it gives me an error message of "Exception: Incorrect range width, was 5 but should be 6". Is this something that has been brought up before, and do you have any potential fixes for this issue?

**Comment by VenturaFranklin** [comment]
@gojiman23 Thank you for reporting this issue! There was an issue with your chapter's submissions sheet. The MSCRs have been submitted successfully.
